#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="angledDuctExplicit"

tutorialPath=`dirname $0`/..
. $tutorialPath/CleanFunctions

wclean $application

for case in $cases
do
    cleanCase $case
done 
