#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="angledDuctExplicit"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

compileApplication $currDir $application

for case in $cases
do
    runApplication blockMesh $case
    runApplication $application $case
done 
