#!/bin/sh
set -x

wmake libso specie
wmake libso thermophysicalFunctions
wmake libso liquids
wmake libso liquidMixture

wmake libso basic
wmake libso combustion
wmake libso laminarFlameSpeed
wmake libso chemistryModel
wmake libso pdfs
