#!/bin/sh
set -x

if [ "$ParaView_DIR" -a -r $ParaView_DIR ] ; then
    wmake libso vtkFoam
    if [ $WM_ARCH == "darwin" ]     
    then
	(cd PVFoamReader; mkdir -p Make/$WM_OPTIONS > /dev/null 2>&1; cd Make/$WM_OPTIONS; cmake ../..; sed -i bak -e 's/.*/& -undefined dynamic_lookup/' CMakeFiles/PVFoamReader.dir/link.txt; make)
    else
	(cd PVFoamReader; mkdir -p Make/$WM_OPTIONS > /dev/null 2>&1; cd Make/$WM_OPTIONS; cmake ../..; make)
    fi
fi
