#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
parentDir=`dirname $PWD`
application=`basename $parentDir`

# make sure the application is compiled
wmake ../$application

runApplication blockMesh
runApplication $application
