#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="boundaryWallFunctions boundaryLaunderSharma boundaryTwoWallsFlowSolution"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

for case in $cases
do

runApplication blockMesh $case
runApplication $application $case

done 
