#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="conjugateCavity"

tutorialPath=`dirname $0`/..
. $tutorialPath/CleanFunctions

for case in $cases
do
    cleanTimeDirectories $case
done

