#!/bin/csh -f
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright held by original author
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     cshrc
#
# Description
#     Startup File for Ensight 8.?.
#     Sourced from .OpenFoam-?.?/cshrc
#
#------------------------------------------------------------------------------

if ($?prompt && $?foamDotFile) then
    if (! $?FOAM_SILENT) then
        echo "Executing: $foamDotFile"
    endif
endif

setenv CEI_HOME /usr/local/ensight/CEI

if ($WM_ARCH == linux) then

    setenv CEI_ARCH linux_2.6_32

else if ($WM_ARCH == linux64) then

#    setenv CEI_ARCH linux_2.4_64
    setenv CEI_ARCH linux_2.6_32

else if ($WM_ARCH == sgiN32 || $WM_ARCH == sgiN32Gcc) then

    setenv CEI_ARCH sgi_6.5_n32

endif


if ( -r $CEI_HOME ) then

    setenv ENSIGHT8_INPUT dummy
    setenv ENSIGHT8_READER $FOAM_LIBBIN
    set path=($path $CEI_HOME/bin)

endif

# -----------------------------------------------------------------------------
