package FoamXServer;


/**
* FoamXServer/ApplicationClassDescriptorListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

abstract public class ApplicationClassDescriptorListHelper
{
  private static String  _id = "IDL:FoamXServer/ApplicationClassDescriptorList:1.0";

  public static void insert (org.omg.CORBA.Any a, FoamXServer.ApplicationClassDescriptor[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FoamXServer.ApplicationClassDescriptor[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = FoamXServer.ApplicationClassDescriptorHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (FoamXServer.ApplicationClassDescriptorListHelper.id (), "ApplicationClassDescriptorList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FoamXServer.ApplicationClassDescriptor[] read (org.omg.CORBA.portable.InputStream istream)
  {
    FoamXServer.ApplicationClassDescriptor value[] = null;
    int _len0 = istream.read_long ();
    value = new FoamXServer.ApplicationClassDescriptor[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = FoamXServer.ApplicationClassDescriptorHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FoamXServer.ApplicationClassDescriptor[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      FoamXServer.ApplicationClassDescriptorHelper.write (ostream, value[_i0]);
  }

}
