package FoamXServer;


/**
* FoamXServer/ApplicationClassDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

public final class ApplicationClassDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String category = null;
  public boolean systemClass = false;

  public ApplicationClassDescriptor ()
  {
  } // ctor

  public ApplicationClassDescriptor (String _name, String _category, boolean _systemClass)
  {
    name = _name;
    category = _category;
    systemClass = _systemClass;
  } // ctor

} // class ApplicationClassDescriptor
