package FoamXServer;


/**
* FoamXServer/DimensionSetListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

public final class DimensionSetListHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.DimensionSet value[] = null;

  public DimensionSetListHolder ()
  {
  }

  public DimensionSetListHolder (FoamXServer.DimensionSet[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.DimensionSetListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.DimensionSetListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.DimensionSetListHelper.type ();
  }

}
