package FoamXServer;

/**
* FoamXServer/FoamXAnyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

public final class FoamXAnyHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.FoamXAny value = null;

  public FoamXAnyHolder ()
  {
  }

  public FoamXAnyHolder (FoamXServer.FoamXAny initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.FoamXAnyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.FoamXAnyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.FoamXAnyHelper.type ();
  }

}
