package FoamXServer;


/**
* FoamXServer/FoamXSYSError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/


// Invalid remote system invocation (e.g. machine can't be reached)
public final class FoamXSYSError extends org.omg.CORBA.UserException
{
  public FoamXServer.ErrorCode errorCode = null;
  public String errorMessage = null;
  public String hostName = null;
  public String methodName = null;
  public String fileName = null;
  public int lineNo = (int)0;

  public FoamXSYSError ()
  {
    super(FoamXSYSErrorHelper.id());
  } // ctor

  public FoamXSYSError (FoamXServer.ErrorCode _errorCode, String _errorMessage, String _hostName, String _methodName, String _fileName, int _lineNo)
  {
    super(FoamXSYSErrorHelper.id());
    errorCode = _errorCode;
    errorMessage = _errorMessage;
    hostName = _hostName;
    methodName = _methodName;
    fileName = _fileName;
    lineNo = _lineNo;
  } // ctor


  public FoamXSYSError (String $reason, FoamXServer.ErrorCode _errorCode, String _errorMessage, String _hostName, String _methodName, String _fileName, int _lineNo)
  {
    super(FoamXSYSErrorHelper.id() + "  " + $reason);
    errorCode = _errorCode;
    errorMessage = _errorMessage;
    hostName = _hostName;
    methodName = _methodName;
    fileName = _fileName;
    lineNo = _lineNo;
  } // ctor

} // class FoamXSYSError
