package FoamXServer;

/**
* FoamXServer/FoamXErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

public final class FoamXErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.FoamXError value = null;

  public FoamXErrorHolder ()
  {
  }

  public FoamXErrorHolder (FoamXServer.FoamXError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.FoamXErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.FoamXErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.FoamXErrorHelper.type ();
  }

}
