package FoamXServer;


/**
* FoamXServer/HostDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

public final class HostDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public boolean alive = false;

  public HostDescriptor ()
  {
  } // ctor

  public HostDescriptor (String _name, boolean _alive)
  {
    name = _name;
    alive = _alive;
  } // ctor

} // class HostDescriptor
