package FoamXServer;


/**
* FoamXServer/JobIDListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

public final class JobIDListHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.JobID value[] = null;

  public JobIDListHolder ()
  {
  }

  public JobIDListHolder (FoamXServer.JobID[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.JobIDListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.JobIDListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.JobIDListHelper.type ();
  }

}
