package FoamXServer;


/**
* FoamXServer/JobID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

public final class JobID implements org.omg.CORBA.portable.IDLEntity
{
  public String hostName = null;

  // Host name.
  public int processID = (int)0;

  public JobID ()
  {
  } // ctor

  public JobID (String _hostName, int _processID)
  {
    hostName = _hostName;
    processID = _processID;
  } // ctor

} // class JobID
