package FoamXServer;


/**
* FoamXServer/SurfacePatch.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:26 AM BST
*/

public final class SurfacePatch implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  // Name of patch
  public String geometricType = null;

  // Optional geometric type
  public int size = (int)0;

  // Size of patch
  public int start = (int)0;

  public SurfacePatch ()
  {
  } // ctor

  public SurfacePatch (String _name, String _geometricType, int _size, int _start)
  {
    name = _name;
    geometricType = _geometricType;
    size = _size;
    start = _start;
  } // ctor

} // class SurfacePatch
