package FoamXServer.CaseServer;

/**
* FoamXServer/CaseServer/IApplicationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public final class IApplicationHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseServer.IApplication value = null;

  public IApplicationHolder ()
  {
  }

  public IApplicationHolder (FoamXServer.CaseServer.IApplication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseServer.IApplicationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseServer.IApplicationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseServer.IApplicationHelper.type ();
  }

}
