package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/ICaseServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public interface ICaseServer extends ICaseServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICaseServer
