package FoamXServer.CaseServer;

/**
* FoamXServer/CaseServer/ICaseServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public final class ICaseServerHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseServer.ICaseServer value = null;

  public ICaseServerHolder ()
  {
  }

  public ICaseServerHolder (FoamXServer.CaseServer.ICaseServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseServer.ICaseServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseServer.ICaseServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseServer.ICaseServerHelper.type ();
  }

}
