package FoamXServer.CaseServer;

/**
* FoamXServer/CaseServer/IGeometricFieldHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public final class IGeometricFieldHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseServer.IGeometricField value = null;

  public IGeometricFieldHolder ()
  {
  }

  public IGeometricFieldHolder (FoamXServer.CaseServer.IGeometricField initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseServer.IGeometricFieldHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseServer.IGeometricFieldHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseServer.IGeometricFieldHelper.type ();
  }

}
