package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IGeometricFieldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public interface IGeometricFieldOperations 
{
  String name ();
  void getInternalFieldValue (FoamXServer.IDictionaryEntryHolder internalFieldValue) throws FoamXServer.FoamXError, FoamXServer.FoamXIOError;
  void getPatchFieldParameters (String patchName, FoamXServer.IDictionaryEntryHolder patchFieldValue) throws FoamXServer.FoamXError, FoamXServer.FoamXIOError;

  // Returns true if this has been modified
  boolean modified ();
} // interface IGeometricFieldOperations
