package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IGeometryDescriptorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public interface IGeometryDescriptorOperations 
{

  //- Name of geometry type (eg, "volume").
  String name ();

  //- Name of geometry type (eg, "volume").
  void name (String newName);

  //- Display name (eg, "Volume").
  String displayName ();

  //- Display name (eg, "Volume").
  void displayName (String newDisplayName);

  //- Description (eg, "Finite Volume Geometry").
  String description ();

  //- Description (eg, "Finite Volume Geometry").
  void description (String newDescription);
} // interface IGeometryDescriptorOperations
