package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IPatchPhysicalTypeDescriptorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public interface IPatchPhysicalTypeDescriptorOperations 
{

  //- Patch physical type name (eg, "inlet").
  String name ();

  //- Patch physical type name (eg, "inlet").
  void name (String newName);
  String displayName ();
  void displayName (String newDisplayName);
  String description ();
  void description (String newDescription);
  String patchType ();
  void patchType (String newPatchType);
  String parentType ();
  void parentType (String newParentType);
  FoamXServer.StringPair[] patchFieldTypes ();
  void patchFieldTypes (FoamXServer.StringPair[] newPatchFieldTypes);
} // interface IPatchPhysicalTypeDescriptorOperations
