package FoamXServer.CaseServer;

/**
* FoamXServer/CaseServer/IPatchPhysicalTypeDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public final class IPatchPhysicalTypeDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseServer.IPatchPhysicalTypeDescriptor value = null;

  public IPatchPhysicalTypeDescriptorHolder ()
  {
  }

  public IPatchPhysicalTypeDescriptorHolder (FoamXServer.CaseServer.IPatchPhysicalTypeDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseServer.IPatchPhysicalTypeDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseServer.IPatchPhysicalTypeDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseServer.IPatchPhysicalTypeDescriptorHelper.type ();
  }

}
