package FoamXServer.CaseBrowser;

/**
* FoamXServer/CaseBrowser/ICaseBrowserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public final class ICaseBrowserHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseBrowser.ICaseBrowser value = null;

  public ICaseBrowserHolder ()
  {
  }

  public ICaseBrowserHolder (FoamXServer.CaseBrowser.ICaseBrowser initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseBrowser.ICaseBrowserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseBrowser.ICaseBrowserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseBrowser.ICaseBrowserHelper.type ();
  }

}
