package FoamXServer.HostBrowser;

/**
* FoamXServer/HostBrowser/IHostBrowserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public final class IHostBrowserHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.HostBrowser.IHostBrowser value = null;

  public IHostBrowserHolder ()
  {
  }

  public IHostBrowserHolder (FoamXServer.HostBrowser.IHostBrowser initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.HostBrowser.IHostBrowserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.HostBrowser.IHostBrowserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.HostBrowser.IHostBrowserHelper.type ();
  }

}
