package FoamXServer.HostBrowser;


/**
* FoamXServer/HostBrowser/IHostBrowser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/


// ---------------------------------------------------------------------
public interface IHostBrowser extends IHostBrowserOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IHostBrowser
