#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="hydrofoil"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

for case in $cases
do
    cleanTimeDirectories $case
done

