#!/bin/sh -v

currDir=`pwd`
application=`basename $currDir`
cases="hydrofoil"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/RunFunctions

for case in $cases
do
    runApplication makeFaMesh $case
    runApplication $application $case
done
