#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright held by original author
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     RunFunctions
#
# Description
#     
#------------------------------------------------------------------------------

runApplication ()
{
    APP_RUN=$1; shift
    if [ -f $1/log.$APP_RUN ] ; then
        echo "$APP_RUN already run on $1: remove log file to run"
    else
        echo "Running $APP_RUN on $1"
        $APP_RUN . $* > $1/log.$APP_RUN 2>&1
    fi
}

runParallel ()
{
    if [ -f $2/log.$1 ] ; then
        echo "$1 already run on $2: remove log file to run"
    else
        if [ "$WM_MPLIB" = "LAM" ]
        then
            echo "Starting LAM using $4 machines file"
            lamboot -v $4
        fi
        echo "Running $1 in parallel on $2 using $3 processes"
        mpirun -np $3 $1 . $2 -parallel < /dev/null > $2/log.$1 2>&1
        if [ "$WM_MPLIB" = "LAM" ]
        then
            echo "Stopping LAM"
            lamclean
        fi
    fi
}

compileApplication ()
{
    echo "Compiling $1/$2 application"
    wmake $1/$2
}

cloneCase ()
{
    if [ -d $2 ] ; then
        echo "Case already cloned: remove case directory $2 to clone"
    else
        echo "Cloning $2 case from $1"
        mkdir $2
        cp -r $1/{0,system,constant} $2
    fi
}

#------------------------------------------------------------------------------
