#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="bubbleColumn bed"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

for case in $cases
do
    runApplication blockMesh $case
    runApplication $application $case
done
