#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
case="ballAndBrick"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh $case
runApplication $application $case

