package FoamXServer.PatchTool;


/**
* FoamXServer/PatchTool/IPatchTool.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* Thursday, December 11, 2003 4:22:22 PM GMT
*/


// ---------------------------------------------------------------------
public interface IPatchTool extends IPatchToolOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPatchTool
