package FoamXServer.PatchTool;


/**
* FoamXServer/PatchTool/IPatchToolHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* Thursday, December 11, 2003 4:22:22 PM GMT
*/


// ---------------------------------------------------------------------
abstract public class IPatchToolHelper
{
  private static String  _id = "IDL:FoamXServer/PatchTool/IPatchTool:1.0";

  public static void insert (org.omg.CORBA.Any a, FoamXServer.PatchTool.IPatchTool that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FoamXServer.PatchTool.IPatchTool extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FoamXServer.PatchTool.IPatchToolHelper.id (), "IPatchTool");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FoamXServer.PatchTool.IPatchTool read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IPatchToolStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FoamXServer.PatchTool.IPatchTool value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FoamXServer.PatchTool.IPatchTool narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FoamXServer.PatchTool.IPatchTool)
      return (FoamXServer.PatchTool.IPatchTool)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FoamXServer.PatchTool._IPatchToolStub stub = new FoamXServer.PatchTool._IPatchToolStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
