package FoamXServer.PatchTool;

/**
* FoamXServer/PatchTool/IPatchToolHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* Thursday, December 11, 2003 4:22:22 PM GMT
*/


// ---------------------------------------------------------------------
public final class IPatchToolHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.PatchTool.IPatchTool value = null;

  public IPatchToolHolder ()
  {
  }

  public IPatchToolHolder (FoamXServer.PatchTool.IPatchTool initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.PatchTool.IPatchToolHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.PatchTool.IPatchToolHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.PatchTool.IPatchToolHelper.type ();
  }

}
