#!/bin/sh
set -x

CURDIR=`pwd`

export RL_ARCH_PATH=$CURDIR/readline-5.0/platforms/$WM_OPTIONS


#
# Build readline if nessecary
#

if [ ! -r $RL_ARCH_PATH/lib/libreadline.so ]
then
    mkdir -p $RL_ARCH_PATH/lib

    cd readline-5.0

    make distclean
    rm -rf $RL_ARCH_PATH

    ./configure --prefix=$RL_ARCH_PATH --enable-static

    make
    make install
    make distclean

    cd $CURDIR
fi


#
# Build setSet (uses RL_ARCH_PATH)
#
wmake setSet
