#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
parentDir=`dirname $PWD`
application=viscoelasticFluidFoam

runApplication blockMesh
runApplication $application
