#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="springDamper sixDOFmotion"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

for case in $cases
do
    runApplication $application $case
done
