package FoamXServer;


/**
* FoamXServer/ApplicationDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class ApplicationDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String category = null;
  public String path = null;
  public boolean systemClass = false;

  public ApplicationDescriptor ()
  {
  } // ctor

  public ApplicationDescriptor (String _name, String _category, String _path, boolean _systemClass)
  {
    name = _name;
    category = _category;
    path = _path;
    systemClass = _systemClass;
  } // ctor

} // class ApplicationDescriptor
