package FoamXServer;

/**
* FoamXServer/CaseDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class CaseDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseDescriptor value = null;

  public CaseDescriptorHolder ()
  {
  }

  public CaseDescriptorHolder (FoamXServer.CaseDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseDescriptorHelper.type ();
  }

}
