package FoamXServer;


/**
* FoamXServer/DictionaryEntryListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class DictionaryEntryListHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.IDictionaryEntry value[] = null;

  public DictionaryEntryListHolder ()
  {
  }

  public DictionaryEntryListHolder (FoamXServer.IDictionaryEntry[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.DictionaryEntryListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.DictionaryEntryListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.DictionaryEntryListHelper.type ();
  }

}
