package FoamXServer;


/**
* FoamXServer/DimensionSet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class DimensionSet implements org.omg.CORBA.portable.IDLEntity
{
  public double mass = (double)0;

  // Kilogramme Kg.
  public double length = (double)0;

  // meter      m.
  public double time = (double)0;

  // second     s.
  public double temperature = (double)0;

  // Kelvin     K.
  public double moles = (double)0;

  // mole       mol.
  public double current = (double)0;

  // Ampere     Amp.
  public double luminousIntensity = (double)0;

  public DimensionSet ()
  {
  } // ctor

  public DimensionSet (double _mass, double _length, double _time, double _temperature, double _moles, double _current, double _luminousIntensity)
  {
    mass = _mass;
    length = _length;
    time = _time;
    temperature = _temperature;
    moles = _moles;
    current = _current;
    luminousIntensity = _luminousIntensity;
  } // ctor

} // class DimensionSet
