package FoamXServer;


/**
* FoamXServer/FloatListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class FloatListHolder implements org.omg.CORBA.portable.Streamable
{
  public float value[] = null;

  public FloatListHolder ()
  {
  }

  public FloatListHolder (float[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.FloatListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.FloatListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.FloatListHelper.type ();
  }

}
