package FoamXServer;

/**
* FoamXServer/HostDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class HostDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.HostDescriptor value = null;

  public HostDescriptorHolder ()
  {
  }

  public HostDescriptorHolder (FoamXServer.HostDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.HostDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.HostDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.HostDescriptorHelper.type ();
  }

}
