package FoamXServer;

/**
* FoamXServer/JobIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class JobIDHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.JobID value = null;

  public JobIDHolder ()
  {
  }

  public JobIDHolder (FoamXServer.JobID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.JobIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.JobIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.JobIDHelper.type ();
  }

}
