package FoamXServer;


/**
* FoamXServer/StringPairListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class StringPairListHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.StringPair value[] = null;

  public StringPairListHolder ()
  {
  }

  public StringPairListHolder (FoamXServer.StringPair[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.StringPairListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.StringPairListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.StringPairListHelper.type ();
  }

}
