package FoamXServer;


/**
* FoamXServer/TypeDescriptorListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FoamX.idl
* Thursday, April 10, 2008 11:16:12 PM BST
*/

public final class TypeDescriptorListHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.ITypeDescriptor value[] = null;

  public TypeDescriptorListHolder ()
  {
  }

  public TypeDescriptorListHolder (FoamXServer.ITypeDescriptor[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.TypeDescriptorListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.TypeDescriptorListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.TypeDescriptorListHelper.type ();
  }

}
