#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="swirlTest"

tutorialPath=`dirname $0`/..
. $tutorialPath/CleanFunctions

for case in $cases
do
    cleanCase $case
    cp $case/0/U.org $case/0/U
done


