#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
case="swirlTest"
utility=setSwirl

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

runApplication blockMesh $case
compileApplication $case $utility
runApplication $utility $case
runApplication $application $case

