#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="mixer2D movingCone movingConeMotion movingConeTopo"

tutorialPath=`dirname $0`/..
. $tutorialPath/CleanFunctions

for case in $cases
do
    cleanCase $case
done 
