#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Get application name from directory
application="rasInterFoam"

cleanCase 
runApplication blockMesh
runApplication setFields
runApplication $application
