#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
case="twoStream"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

runApplication blockMesh $case
runApplication $application $case

