#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
case="channelParticles"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Compile tutorial-specific application
compileApplication icoLagrangianFoam

(cd $case; runApplication blockMesh)
(cd $case; runApplication $application)

