package FoamXServer.PatchToolServer;


/**
* FoamXServer/PatchToolServer/IPatchToolServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:27 AM BST
*/


// ---------------------------------------------------------------------
public interface IPatchToolServer extends IPatchToolServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPatchToolServer
