package FoamXServer.PatchToolServer;


/**
* FoamXServer/PatchToolServer/IPatchToolServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PatchTool.idl
* Friday, September 7, 2007 12:01:27 AM BST
*/


// ---------------------------------------------------------------------
abstract public class IPatchToolServerHelper
{
  private static String  _id = "IDL:FoamXServer/PatchToolServer/IPatchToolServer:1.0";

  public static void insert (org.omg.CORBA.Any a, FoamXServer.PatchToolServer.IPatchToolServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FoamXServer.PatchToolServer.IPatchToolServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FoamXServer.PatchToolServer.IPatchToolServerHelper.id (), "IPatchToolServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FoamXServer.PatchToolServer.IPatchToolServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IPatchToolServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FoamXServer.PatchToolServer.IPatchToolServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FoamXServer.PatchToolServer.IPatchToolServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FoamXServer.PatchToolServer.IPatchToolServer)
      return (FoamXServer.PatchToolServer.IPatchToolServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FoamXServer.PatchToolServer._IPatchToolServerStub stub = new FoamXServer.PatchToolServer._IPatchToolServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FoamXServer.PatchToolServer.IPatchToolServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FoamXServer.PatchToolServer.IPatchToolServer)
      return (FoamXServer.PatchToolServer.IPatchToolServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FoamXServer.PatchToolServer._IPatchToolServerStub stub = new FoamXServer.PatchToolServer._IPatchToolServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
